# Generated by Django 5.2.5 on 2025-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "Global Permissions",
                "verbose_name_plural": "Global Permissions",
                "permissions": [("ffs", "FFS")],
            },
        ),
    ]
