# Generated by Django 5.2.5 on 2025-09-11 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("private", "0002_settings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Settings",
            new_name="Setting",
        ),
    ]
