# Generated by Django 5.2.5 on 2025-09-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0003_rename_settings_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilePacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(blank=True, max_length=128)),
                ("file", models.FileField(upload_to="files")),
            ],
        ),
    ]
