# Generated by Django 5.2.5 on 2025-09-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0004_filepacket"),
    ]

    operations = [
        migrations.AddField(
            model_name="filepacket",
            name="upload_date",
            field=models.DateTimeField(null=True),
        ),
    ]
