# Generated by Django 5.2.5 on 2025-09-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0006_alter_filepacket_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="filepacket",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILED", "FAILED"),
                    ("OUTSTANDING", "OUTSTANDING"),
                    ("STORED", "STORED"),
                ],
                default="OUTSTANDING",
                max_length=20,
            ),
        ),
    ]
