# Generated by Django 5.2.5 on 2025-09-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0007_filepacket_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filepacket",
            old_name="hash",
            new_name="hsh",
        ),
    ]
