# Generated by Django 5.2.5 on 2025-09-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0008_rename_hash_filepacket_hsh"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filepacket",
            name="id",
        ),
        migrations.AlterField(
            model_name="filepacket",
            name="hsh",
            field=models.CharField(
                blank=True, max_length=128, primary_key=True, serialize=False
            ),
        ),
    ]
