# Generated by Django 5.2.5 on 2025-09-18 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0009_remove_filepacket_id_alter_filepacket_hsh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepacket",
            name="upload_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
