# Generated by Django 5.2.5 on 2025-09-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0010_alter_filepacket_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepacket",
            name="file",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
