# Generated by Django 5.2.5 on 2025-09-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0011_alter_filepacket_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepacket",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "NEW"),
                    ("FAILED", "FAILED"),
                    ("OUTSTANDING", "OUTSTANDING"),
                    ("STORED", "STORED"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
