# Generated by Django 5.2.5 on 2025-09-20 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0012_alter_filepacket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="filepacket",
            name="last_used",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filepacket",
            name="upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
