# Generated by Django 5.2.5 on 2025-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0013_filepacket_last_used_alter_filepacket_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepacket",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "NEW"),
                    ("FAILED", "FAILED"),
                    ("PENDING", "PENDING"),
                    ("STORED", "STORED"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
