# Generated by Django 5.2.5 on 2025-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0014_alter_filepacket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepacket",
            name="last_used",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="filepacket",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
