# Generated by Django 5.2.5 on 2025-09-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0015_alter_filepacket_last_used_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
