# Generated by Django 5.2.5 on 2025-09-20 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0016_delete_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepacket",
            name="last_used",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="filepacket",
            name="upload_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
