# Generated by Django 5.2.5 on 2025-09-20 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0017_alter_filepacket_last_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepacket",
            name="last_used",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="filepacket",
            name="upload_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
