# Generated by Django 5.2.5 on 2025-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0018_alter_filepacket_last_used_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionsRule",
            fields=[
                (
                    "rule",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("users", models.CharField(max_length=128)),
                ("is_template", models.BooleanField(default=False)),
            ],
        ),
    ]
