# Generated by Django 4.2.11 on 2025-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "Global Permission holder",
                "verbose_name_plural": "Global Permission holders",
                "permissions": [
                    ("admin_access", "Can access developer admin"),
                    ("dev_admin", "Can access dev admin pages"),
                ],
            },
        ),
    ]
