# Generated by Django 4.2.11 on 2025-09-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalpermission",
            options={
                "permissions": [("admin", "Admin functions")],
                "verbose_name": "Global Permissions",
                "verbose_name_plural": "Global Permissions",
            },
        ),
    ]
