# Generated by Django 5.2.5 on 2025-09-10 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0002_alter_globalpermission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalpermission",
            options={
                "permissions": [("admin", "Admin functions"), ("ffs", "FFS")],
                "verbose_name": "Global Permissions",
                "verbose_name_plural": "Global Permissions",
            },
        ),
    ]
