# Generated by Django 5.2.5 on 2025-09-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0004_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalpermission",
            options={
                "permissions": [("admin", "Admin functions")],
                "verbose_name": "Global Permissions",
                "verbose_name_plural": "Global Permissions",
            },
        ),
    ]
